'use client'

import './globals.css'
import React from 'react'
import { Template } from '@/components/Template'
import { Providers } from '@/redux/provider'
import { QueryClient, QueryClientProvider } from 'react-query'

// import type { Metadata } from "next";
// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

type RootLayoutProps = {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  const queryClient = new QueryClient()

  return (
    <html>
      <body className="flex h-screen flex-row items-center justify-end gap-7 bg-white text-zinc-600 selection:bg-sky-400 selection:text-white lg:p-7">
        <QueryClientProvider client={queryClient}>
          <Providers>
            <Template.Root>{children}</Template.Root>
          </Providers>
        </QueryClientProvider>
      </body>
    </html>
  )
}
